### ISSUE TITLE
It is a empty react app

### ISSUE THREAD

**Issue by fearsd** [ksielyov/social_network#1]
It is a empty react app. You should type this commands in your shell:
`git add .`
`git commit -m "to make repo full"`
`git push`

**Comment by ksielyov** [comment]
Thank you, that was changed.

**Comment by fearsd** [comment]
Ok, zyabl

**Comment by tlrist** [comment]
What is going on here?

**Comment by fearsd** [comment]
> What is going on here?

We are flexing here
